#include "globaldefine.h"
#include <QStandardPaths>
#include <QString>

QString CLOUD_HOST_NHA_DAT = "";
QString FTP_HOST = "";
QString IMAGE_HOST = "";
QString CLOUD_HOST_LAMAPPDIDONG = "";
QString GOOGLE_CLOUD_HOST = "";
QString LOCAL_HOST = "";
QString QUERY_MUABANDOTNET = LOCAL_HOST + "/scrapmuaban?requesturl=";
QString QUERY_CHOTOTDOTCOM = LOCAL_HOST + "/scrapchotot?requesturl=";
QString QUERY_DOTHIDOTNET = LOCAL_HOST + "/scrapdothi?requesturl=";
QString QUERY_NHABANSGDOTVN = LOCAL_HOST + "/scrapnhabansg?requesturl=";
QString QUERY_BANNHASGDOTCOM = LOCAL_HOST + "/scrapbannhasg?requesturl=";
QString QUERY_MUABANNHADATDOTVN = LOCAL_HOST + "/scrapmuaban?requesturl=";
QString QUERY_BATDONGSANDOTCOMDOTVN = LOCAL_HOST + "/scrapbatdongsan?requesturl=";
QString API_CHOTOT_CHUNGCU = "https://gateway.chotot.com/v1/public/ad-listing?region=13&cg=1010&w=1&limit=20&st=s&o=20";
QString API_CHOTOT_NHAO = "https://gateway.chotot.com/v1/public/ad-listing?region=13&cg=1020&w=1&limit=20&st=s&o=20";
QString API_CHOTOT_DAT = "https://gateway.chotot.com/v1/public/ad-listing?region=13&cg=1040&w=1&limit=20&st=s&o=20";

#ifdef Q_OS_WIN
QString STORAGE_PATH = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);
QString LOGIN_INFO = STORAGE_PATH + "/Storage.xml";
#else
QString STORAGE_PATH = QStandardPaths::AppDataLocation + "\\resource\\xml\\";
QString LOGIN_INFO = STORAGE_PATH + "Storage.xml";
#endif
QString DBTYPE = "QSQLITE";
QString DBNAME_DATA_MANAGEMENT = "DataManagementDb";
QString DBFILENAME_EXTENSION = ".db";
QString DBFILENAME_DATA_MANAGEMENT = DBNAME_DATA_MANAGEMENT + DBFILENAME_EXTENSION;
QString DBCON_DATA_MANAGEMENT = DBNAME_DATA_MANAGEMENT;
QString DBTBL_BDS_DATA = "tblData";

QString PARAM_MARK = "?roleId=1&";
QString PARAM_LOAIBDS = "loaibds=";
QString PARAM_QUANHUYEN = "quanhuyen=";
QString PARAM_TOKENKEY = "tokenKey=";
QString LOAIBDS_BIETTHU = "bietthu";
QString LOAIBDS_CHUNGCU = "chungcu";
QString LOAIBDS_NHAHEM = "nhahem";
QString LOAIBDS_NHAPHO = "nhapho";
QString LOAIBDS_DATDUAN = "datduan";
QString LOAIBDS_DAT = "dat";
QString LOAIBDS_KHAC = "khac";
QString AND = "&";
QString QUANHUYEN_1 = "Quận 1";
QString QUANHUYEN_2 = "Quận 2";
QString QUANHUYEN_3 = "Quận 3";
QString QUANHUYEN_4 = "Quận 4";
QString QUANHUYEN_5 = "Quận 5";
QString QUANHUYEN_6 = "Quận 6";
QString QUANHUYEN_7 = "Quận 7";
QString QUANHUYEN_8 = "Quận 8";
QString QUANHUYEN_9 = "Quận 9";
QString QUANHUYEN_10 = "Quận 10";
QString QUANHUYEN_11 = "Quận 11";
QString QUANHUYEN_12 = "Quận 12";
QString QUANHUYEN_PHUNHUAN = "Quận Phú Nhuận";
QString QUANHUYEN_BINHTHANH = "Quận Bình Thạnh";
QString QUANHUYEN_TANBINH = "Quận Tân Bình";
QString QUANHUYEN_TANPHU = "Quận Tân Phú";
QString QUANHUYEN_GOVAP = "Quận Gò Vấp";
QString QUANHUYEN_THUDUC = "Quận Thủ Đức";
QString QUANHUYEN_BINHTAN = "Quận Bình Tân";
QString QUANHUYEN_BINHCHANH = "Huyện Bình Chánh";
QString QUANHUYEN_CUCHI = "Huyện Củ Chi";
QString QUANHUYEN_NHABE = "Huyện Nhà Bè";
QString QUANHUYEN_CANGIO = "Huyện Cần Giờ";
QString QUANHUYEN_HOCMON = "Huyện Hóc Môn";

QString DEFAULT_TINHTHANH = "TP Hồ Chí Minh";
QString DEFAULT_QUANHUYEN = QUANHUYEN_GOVAP;
QString DEFAULT_PHUONGXA = "Phường 1";
QString DEFAULT_TENDUONG = "";

QString DEFAULT_TEXT = "";
int DEFAULT_SELECTED_ID = -1;
int DEFAULT_INT_VALUE = -1;
int DEFAULT_KEY = -1;

int POINT_PROVINCE = 0;
int POINT_DISTRICT = 0;
int POINT_WARD = 1;
int POINT_TYPE = 1;
int POINT_HOMENUMBER = 10;
int POINT_STREETNAME = 1;
int POINT_POSITION = 1;
int POINT_STREETWIDTH =5;
int POINT_PROJECTNAME = 1;
int POINT_WIDTH = 2;
int POINT_LONG = 2;
int POINT_DEFAULTSQUARE = 2;
int POINT_REALITYSQUARE = 2;
int POINT_ROADSQUARE = 3;
int POINT_SHAPE = 1;
int POINT_LANDPLANNINGTYPE = 3;
int POINT_AGRICULTURELANDSQUARE = 2;
int POINT_DIRECTION = 1;
int POINT_CONSTRUCTIONSQUARE = 3;
int POINT_FLOORSQUARE = 1;
int POINT_FLOORS = 1;
int POINT_CONSTRUCTIONHEIGHT = 2;
//int POINT_VATLIEUHOANTHIEN = 1;
//int POINT_TIENICHNHA = 2;
int POINT_USINGSTATUS = 2;
int POINT_QUALITY = 2;
int POINT_PRICE = 3;
int POINT_PRICEUNIT = 1;
int POINT_DISCUSSEDPRICE = 5;
int POINT_JURIDICAL = 2;
int POINT_JURIDICALSTATUS = 2;
int POINT_OWNERNAME = 2;
int POINT_OWNERAGE = 1;
int POINT_OWNERGENDER = 1;
int POINT_OWNERPHONE = 5;
int POINT_OWNERADDRESS = 2;

int POINT_IMAGEMATTIEN = 3;
int POINT_IMAGELEFT = 1;
int POINT_IMAGERIGHT = 1;
int POINT_IMAGEOPPOSITE = 1;
int POINT_LIVINGROOM = 2;
int POINT_KITCHEN = 2;
int POINT_BEDROOM = 2;
int POINT_TOILET = 2;
int POINT_TERRACE = 2;
int POINT_YARD = 2;
int POINT_GARAGE = 2;

int POINT_TIENICHTRONGNHA = 2;
int POINT_COMPLETETYPES = 2;

int POINT_VIDEONHA = 10;
int POINT_IMAGE360DEGREE = 10;
int POINT_IMAGEPOSITION = 5;

int POINT_IMAGE_HOUSE = 10;
int POINT_IMAGE_JURIDICAL = 10;
int POINT_IMAGE_LANDPLANNING = 10;
//int POINT_IMAGEQUYHOACHSUDUNGDAT = 10;

int POINT_CONTACTTYPE = 1;
int POINT_CONTACTNAME = 2;
int POINT_CONTACTAGE = 1;
int POINT_CONTACTGENDER = 1;
int POINT_CONTACTPHONE = 5;
int POINT_CONTACTADDRESS = 2;
int POINT_CONTACTCOMPANY = 1;

QString c_NHADATVN_IMAGE_TYPE_HOUSE = "House";
//QString IMAGE_TYPE_MATTIEN = "mattien";
//QString IMAGE_TYPE_VIEWTRAIPHAI = "viewtraiphai";
//QString IMAGE_TYPE_PHONGKHACH = "phongkhach";
//QString IMAGE_TYPE_PHONGBEP = "mattien";
//QString IMAGE_TYPE_PHONGNGU = "mattien";
//QString IMAGE_TYPE_PHONGTAM = "mattien";
//QString IMAGE_TYPE_SANTHUONG = "santhuong";
//QString IMAGE_TYPE_NHAXE = "nhaxe";
QString c_NHADATVN_IMAGE_TYPE_JURIDICAL = "Sovereignty";
QString c_NHADATVN_IMAGE_TYPE_LANDPLANNING = "LandPlaning";
//QString IMAGE_TYPE_QUYHOACHSUDUNGDAT = "quyhoachsudungdat";

uint32_t BILLION = 1000000000;
uint32_t MILLION = 1000000;
uint16_t DEFAULT_INTERVAL = 5000;
int MAX_NETWORK_THREAD = 3;

QString c_NHADATVN_Id = "Id";
QString c_NHADATVN_Name = "Name";
QString c_NHADATVN_ParentId = "ParentId";
QString c_NHADATVN_DisplayName = "DisplayName";
QString c_NHADATVN_Type = "Type";
QString c_NHADATVN_HomeNumber = "HomeNumber";
QString c_NHADATVN_Street = "Street";
QString c_NHADATVN_Ward = "Ward";
QString c_NHADATVN_District = "District";
QString c_NHADATVN_Province = "Province";
QString c_NHADATVN_ProjectName = "ProjectName";
QString c_NHADATVN_StreetWidth = "StreetWidth";
QString c_NHADATVN_Position = "Position";
QString c_NHADATVN_Direction = "Direction";
QString c_NHADATVN_DefaultSquare = "DefaultSquare";
QString c_NHADATVN_RealitySquare = "RealitySquare";
QString c_NHADATVN_PriceUnit = "PriceUnit";
QString c_NHADATVN_Price = "Price";
QString c_NHADATVN_DiscussedPrice = "DiscussedPrice";
QString c_NHADATVN_ConstructionSquare = "ConstructionSquare";
QString c_NHADATVN_FloorSquare = "FloorSquare";
QString c_NHADATVN_Floors = "Floors";
QString c_NHADATVN_ConstructionHeight = "Height";
QString c_NHADATVN_UsingStatus = "UsingStatus";
QString c_NHADATVN_Complete = "Complete";
QString c_NHADATVN_Longitude = "Longitude";
QString c_NHADATVN_Latitude = "Latitude";
QString c_NHADATVN_BedRooms = "BedRooms";
QString c_NHADATVN_Toilets = "Toilets";
QString c_NHADATVN_LivingRoom = "LivingRoom";
QString c_NHADATVN_Kitchen = "Kitchen";
QString c_NHADATVN_Quality = "Quality";
QString c_NHADATVN_InfomationType = "InfomationType";
QString c_NHADATVN_SubmitStatus = "SubmitStatus";
QString c_NHADATVN_CollectionPoints = "CollectionPoints";
QString c_NHADATVN_CreatedDate = "CreatedDate";
QString c_NHADATVN_Terrace = "Terrace";
QString c_NHADATVN_Yard = "Yard";
QString c_NHADATVN_Garage = "Garage";
QString c_NHADATVN_Shape = "Shape";
QString c_NHADATVN_Wide = "Wide";
QString c_NHADATVN_Long = "Long";
QString c_NHADATVN_AgriculturalLandSquare = "AgriculturalLandSquare";
QString c_NHADATVN_LandPlanningType = "LandPlanningType";
QString c_NHADATVN_RoadSquare = "RoadSquare";
QString c_NHADATVN_Juridical = "Juridical";
QString c_NHADATVN_JuridicalStatus = "JuridicalStatus";
QString c_NHADATVN_Land = "Land";
QString c_NHADATVN_FullName = "FullName";
QString c_NHADATVN_Age = "Age";
QString c_NHADATVN_Phone = "Phone";
QString c_NHADATVN_Gender = "Gender";
QString c_NHADATVN_Address = "Address";
QString c_NHADATVN_Company = "Company";
QString c_NHADATVN_Email = "Email";
QString c_NHADATVN_Host = "Host";
QString c_NHADATVN_Contact = "Contact";
QString c_NHADATVN_ID = "ID";
QString c_NHADATVN_Link = "Link";
QString c_NHADATVN_DataSources = "DataSources";
QString c_NHADATVN_DateOfPost = "DateOfPost";
QString c_NHADATVN_Source = "Source";
QString c_NHADATVN_SourceLink = "SourceLink";
QString c_NHADATVN_Note = "Note";

QString c_CRAWL_loaibds = "loaibds";
QString c_CRAWL_diachi = "diachi";
QString c_CRAWL_tenduong = "tenduong";
QString c_CRAWL_phuongxa = "phuongxa";
QString c_CRAWL_quanhuyen = "quanhuyen";
QString c_CRAWL_tinhthanh = "tinhthanh";
QString c_CRAWL_tenduan = "tenduan";
QString c_CRAWL_duongvao = "duongvao";
QString c_CRAWL_huongnha = "huongnha";
QString c_CRAWL_giametvuong = "giametvuong";
QString c_CRAWL_gia = "gia";
QString c_CRAWL_dientichxaydung = "dientichxaydung";
QString c_CRAWL_dientichsudung = "dientichsudung";
QString c_CRAWL_dientichdat = "dientichdat";
QString c_CRAWL_sotang = "sotang";
QString c_CRAWL_sophongngu = "sophongngu";
QString c_CRAWL_sotoilet = "sotoilet";
QString c_CRAWL_phaply = "phaply";
QString c_CRAWL_ten = "ten";
QString c_CRAWL_sodienthoai = "sodienthoai";
QString c_CRAWL_email = "email";
QString c_CRAWL_ngaydang = "ngaydang";
QString c_CRAWL_nguon = "nguon";
QString c_CRAWL_pageurl = "pageurl";
QString c_CRAWL_tieude = "tieude";
QString c_CRAWL_noidung = "noidung";
QString c_CRAWL_hinhanh = "hinhanh";
